import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

// Treat unused vars/args/caught-errors as ignorable when prefixed with "_".
// Matches the convention used throughout the codebase (e.g. `catch (_e)`).
const UNUSED_VAR_OPTS = {
  argsIgnorePattern: '^_',
  varsIgnorePattern: '^_',
  caughtErrorsIgnorePattern: '^_',
  destructuredArrayIgnorePattern: '^_',
}

export default defineConfig([
  globalIgnores(['dist']),

  // Service worker (background.js) — Chrome extension worker globals.
  {
    files: ['src/background.js'],
    languageOptions: {
      globals: { ...globals.serviceworker, chrome: 'readonly', fetch: 'readonly' },
    },
  },

  // Legacy JS/JSX files (background.js, theme-init.js, etc.)
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      'no-unused-vars': ['error', UNUSED_VAR_OPTS],
    },
  },

  // TS/TSX — full migration target.
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      ...tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', UNUSED_VAR_OPTS],
      // React Compiler advisory rules (eslint-plugin-react-hooks v6+).
      // These flag patterns the React Compiler can't optimize, but the
      // patterns themselves are correct and the app works. Surface as
      // warnings so they're visible without blocking CI.
      'react-hooks/refs': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/immutability': 'warn',
    },
  },

  // shadcn UI primitives: file exports both the component and variants.
  // The pattern is generated by the shadcn CLI — leave alone.
  {
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
